import type { SiteButton } from "@/types/database";

/** Default fan-facing buttons — seeded to DB; admins can change label + href. */
export const SITE_BUTTON_DEFAULTS: Omit<SiteButton, "updated_at">[] = [
  // Navbar & footer — public
  {
    id: "btn-navbar-home",
    button_key: "navbar.home",
    section: "Navigation",
    label: "Home",
    href: "/",
    description: "Top menu and footer — Home",
    is_active: true,
    sort_order: 1,
    open_in_new_tab: false,
  },
  {
    id: "btn-navbar-communities",
    button_key: "navbar.communities",
    section: "Navigation",
    label: "Communities",
    href: "/communities",
    description: "Top menu and footer — Communities",
    is_active: true,
    sort_order: 2,
    open_in_new_tab: false,
  },
  {
    id: "btn-navbar-giveaways",
    button_key: "navbar.giveaways",
    section: "Navigation",
    label: "Giveaways",
    href: "/giveaways",
    description: "Top menu and footer — Giveaways (logged-in fans)",
    is_active: true,
    sort_order: 3,
    open_in_new_tab: false,
  },
  {
    id: "btn-navbar-meet-greet",
    button_key: "navbar.meet_greet",
    section: "Navigation",
    label: "Meet & Greet",
    href: "/meet-and-greet",
    description: "Top menu and footer — Meet & Greet (logged-in fans)",
    is_active: true,
    sort_order: 4,
    open_in_new_tab: false,
  },
  {
    id: "btn-navbar-contact",
    button_key: "navbar.contact",
    section: "Navigation",
    label: "Private DMs",
    href: "/contact",
    description: "Top menu and footer — Private DMs (logged-in fans)",
    is_active: true,
    sort_order: 5,
    open_in_new_tab: false,
  },
  {
    id: "btn-navbar-login",
    button_key: "navbar.login",
    section: "Navigation",
    label: "Log in",
    href: "/login",
    description: "Top menu — Log in (guests)",
    is_active: true,
    sort_order: 6,
    open_in_new_tab: false,
  },
  {
    id: "btn-navbar-signup",
    button_key: "navbar.signup",
    section: "Navigation",
    label: "Sign up",
    href: "/signup",
    description: "Top menu — Sign up (guests)",
    is_active: true,
    sort_order: 7,
    open_in_new_tab: false,
  },
  {
    id: "btn-navbar-dashboard",
    button_key: "navbar.dashboard",
    section: "Navigation",
    label: "Dashboard",
    href: "/dashboard",
    description: "Top menu — Dashboard (logged-in fans)",
    is_active: true,
    sort_order: 8,
    open_in_new_tab: false,
  },
  {
    id: "btn-navbar-admin",
    button_key: "navbar.admin",
    section: "Navigation",
    label: "Admin",
    href: "/admin",
    description: "Top menu — Admin panel (admins only)",
    is_active: true,
    sort_order: 9,
    open_in_new_tab: false,
  },
  // Home page — guest CTA
  {
    id: "btn-home-guest-primary",
    button_key: "home.cta.guest_primary",
    section: "Home page",
    label: "Create Account",
    href: "/signup",
    description: "Landing page bottom — main button for guests",
    is_active: true,
    sort_order: 10,
    open_in_new_tab: false,
  },
  {
    id: "btn-home-guest-secondary",
    button_key: "home.cta.guest_secondary",
    section: "Home page",
    label: "Log In",
    href: "/login",
    description: "Landing page bottom — secondary button for guests",
    is_active: true,
    sort_order: 11,
    open_in_new_tab: false,
  },
  // Home page — member CTA
  {
    id: "btn-home-member-primary",
    button_key: "home.cta.member_primary",
    section: "Home page",
    label: "Go to Dashboard",
    href: "/dashboard",
    description: "Landing page bottom — main button for logged-in fans",
    is_active: true,
    sort_order: 12,
    open_in_new_tab: false,
  },
  {
    id: "btn-home-member-secondary",
    button_key: "home.cta.member_secondary",
    section: "Home page",
    label: "Browse Communities",
    href: "/communities",
    description: "Landing page bottom — secondary button for logged-in fans",
    is_active: true,
    sort_order: 13,
    open_in_new_tab: false,
  },
  // Home page — feature cards
  {
    id: "btn-home-feature-giveaways",
    button_key: "home.feature.giveaways",
    section: "Home page",
    label: "Giveaways",
    href: "/giveaways",
    description: "Home feature card — Giveaways (logged-in fans)",
    is_active: true,
    sort_order: 14,
    open_in_new_tab: false,
  },
  {
    id: "btn-home-feature-meet-greet",
    button_key: "home.feature.meet_greet",
    section: "Home page",
    label: "Meet & Greet",
    href: "/meet-and-greet",
    description: "Home feature card — Meet & Greet (logged-in fans)",
    is_active: true,
    sort_order: 15,
    open_in_new_tab: false,
  },
  {
    id: "btn-home-feature-communities-guest",
    button_key: "home.feature.communities_guest",
    section: "Home page",
    label: "Communities",
    href: "/signup",
    description: "Home feature card — Communities (guests, before sign up)",
    is_active: true,
    sort_order: 16,
    open_in_new_tab: false,
  },
  {
    id: "btn-home-feature-communities-member",
    button_key: "home.feature.communities_member",
    section: "Home page",
    label: "Communities",
    href: "/communities",
    description: "Home feature card — Communities (logged-in fans)",
    is_active: true,
    sort_order: 17,
    open_in_new_tab: false,
  },
  {
    id: "btn-home-feature-contact",
    button_key: "home.feature.contact",
    section: "Home page",
    label: "Private DMs",
    href: "/contact",
    description: "Home feature card — Private DMs (logged-in fans)",
    is_active: true,
    sort_order: 18,
    open_in_new_tab: false,
  },
  // Communities page
  {
    id: "btn-community-guest-join",
    button_key: "community.guest_join",
    section: "Communities",
    label: "Sign up to join",
    href: "/signup",
    description: "When a guest clicks a community card — where they go instead of Telegram",
    is_active: true,
    sort_order: 19,
    open_in_new_tab: false,
  },
];
